### PR TITLE
revert(merge) reverted merged changes

### LINKED ISSUE #77: wrong order merge
#75 made #74 obsolete. my bad I should have noted that. #74 actually reverted some code which now causes an error. 

I'll create a PR for it.

### PR DESCRIPTION
**Pull request by pixelass**
pull request was obsolete and caused errors when merged

closes #77

### CODE REVIEW

**Comment by igorlino** [comment]
I have included you as a collaborator, you may commit  directly to the repo.  (In case there is anything you would like to change .)

**Comment by coder4589** [comment]
Hi @pixelass ,

The post link below is from jQuery Forum! If you know how to help me with this problem, please let me know! Thanks!

elevateZoom jQuery Plugin - How to hide ZoomLens when the mouse is not hover the images?

https://forum.jquery.com/topic/elevatezoom-jquery-plugin-how-to-hide-zoomlens-when-the-mouse-is-not-hover-the-images

**Comment by pixelass** [comment]
I actually started a rewrite of this plugin. After my next conference I will look into it and release a new version for this plugin. 

@coder4589 can you open a new issue for this?
I will try to include most issues and feature requests in the new version.

**Comment by pixelass** [comment]
@coder4589 is this the same issue as mentioned in #80 ?

**Comment by coder4589** [comment]
Hi @pixelass ,

First of all, good luck at your next conference ...

Yes it is the same issue mentioned in #80 (I will update the issue's post!)

I really hope somebody revives this plugin, because truth to be said if I'm not wrong, elevateZoom is one of the best, if not the best, jQuery image zoom plugin out there!

It would be nice to implement a Browser Screen Mode too if possible as mentioned in this issue #83 

I made 2 modifications from the last commit ([1.1.21 - 25 days ago](https://github.com/igorlino/elevatezoom-plus/blob/master/src/jquery.ez-plus.js)) as you can see in [this link](https://forum.jquery.com/topic/elevatezoom-plus-screen-mode-help-needed#14737000007282001)! One is to invert Mouse Scroll and the other to change minZoomIn default level! Can you please tell me if the modifications may cause any problems while using the plugin or if I should use any other better alternative?

by the way, thanks for your fast reply!

**Pull request merged**
